// This file auto-generated by grunit gem
#import <UIKit/UIKit.h>

int main(int argc, char *argv[]) {
  @autoreleasepool {
    return UIApplicationMain(argc, argv, nil, @"GRUnitIOSAppDelegate");
  }
}
